### ISSUE TITLE
Add configuration options for default flags

### ISSUE THREAD

**Issue by RoboMWM** [dwilson390/MyChunk#1]
Hi, I'd like to change the default flags for PvP and Mobs to true instead of false, as I only want simple chunk protection.

**Comment by dwilson390** [comment]
Apologies for this very late response. I haven't been working on this project in ages however, I am now attempting to pick it up.

I'll attempt to get this added today as a configuration option.

**Comment by dwilson390** [comment]
Added in latest commit. Release will be available shortly, I have a few extra issues to fix before releasing v1.6.1.

**Comment by dwilson390** [comment]
I have just released a new version which includes this feature.

https://github.com/dwilson390/MyChunk/releases/tag/v1.6.1

Simply change `default_allow_mobs: false` to `default_allow_mobs: true` and `default_allow_pvp: false` to `default_allow_pvp: true`
