### ISSUE TITLE
Compatible with WorldGuard 6 Beta 4?

### ISSUE THREAD

**Issue by RoboMWM** [dwilson390/MyChunk#2]
What exactly does MyChunk do with WorldGuard? If it's to prevent the use of claiming via a command in an already-defined region, then I've got that covered by only allowing use of signs.

**Comment by dwilson390** [comment]
To answer the question in the title. v1.6.1 will add this compatibility if it is not already there (I am nearly sure it is however).

To answer the question in the comment. As of now, hardly anything. The plugin should work correctly without it.

**Comment by dwilson390** [comment]
v1.6.1 has been released.

**Fixed and closed**
