### ISSUE TITLE
Blocks are able to be placed in claimed chunks

### ISSUE THREAD

**Issue by MrsWiccan** [dwilson390/MyChunk#3]
Blocks are able to be placed and broken in plots however the chest and other functions still work.  I tried to update the WorldGuard and it broke even worse spamming errors everywhere in my console.

**Comment by dwilson390** [comment]
Unable to recreate your issue.

Could you please provide a list of plugins and their versions. Also, if possible could you please show any errors?

**Comment by dwilson390** [comment]
Since this seems similar to the issue I recently fixed, I am closing this issue as I believe it to be fixed. Please reply if your issue is not fixed with this version: https://files.dwilson.me.uk/MyChunk-1.6.1.jar.
